# -*- coding: utf-8 -*-
"""Arch_Technology_Internship_ML-Project_1stTask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N3CC0l1qVfyRm5d5akJDAVAWAl9-HDrs
"""

from google.colab import drive
drive.mount('/content/drive')

file_path = "/content/drive/MyDrive/spam.csv"

import pandas as pd
import re
import nltk
import matplotlib.pyplot as plt


from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

from sklearn.linear_model import LogisticRegression

from imblearn.over_sampling import SMOTE

df = pd.read_csv(file_path, encoding='latin-1')
df = df[['v1', 'v2']]
df.columns = ['label', 'text']

df.head()

df['label'] = df['label'].map({'ham': 0, 'spam': 1})

nltk.download('stopwords')

stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()

def preprocess(text):
    text = text.lower()
    text = re.sub('[^a-z]', ' ', text)

    words = text.split()
    words = [w for w in words if w not in stop_words]
    words = [stemmer.stem(w) for w in words]

    return ' '.join(words)

df['text'] = df['text'].apply(preprocess)

vectorizer = TfidfVectorizer(
    max_features=10000,
    ngram_range=(1,2),
    min_df=2,
    max_df=0.9
)

X = vectorizer.fit_transform(df['text']).toarray()
y = df['label']

import matplotlib.pyplot as plt

# Apply SMOTE
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

print("Before:")
print(pd.Series(y).value_counts())

print("\nAfter:")
print(pd.Series(y_resampled).value_counts())


# Before balancing
before_counts = pd.Series(y).value_counts()

# After balancing
after_counts = pd.Series(y_resampled).value_counts()


plt.figure(figsize=(10,5))

# Plot BEFORE
plt.subplot(1,2,1)
before_counts.plot(kind='bar')
plt.title("Before SMOTE (Imbalanced)")
plt.xlabel("Class")
plt.ylabel("Count")

# Plot AFTER
plt.subplot(1,2,2)
after_counts.plot(kind='bar')
plt.title("After SMOTE (Balanced)")
plt.xlabel("Class")
plt.ylabel("Count")

# Show plots
plt.tight_layout()
plt.show()

X_train, X_test, y_train, y_test = train_test_split(
    X_resampled, y_resampled, test_size=0.2, random_state=42
)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

def predict_email(text):
    text = preprocess(text)
    vector = vectorizer.transform([text]).toarray()
    result = model.predict(vector)

    return "Spam" if result[0] == 1 else "Not Spam"



print(predict_email("Project submission tomorrow. Win cash now"))
print(predict_email("Your friend shared notes. Also get free entry in competition"))
print(predict_email("Security alert: login detected. Win free protection package"))
print(predict_email("Please send me the assignment file"))
print(predict_email("Click here to win a free iPhone"))

import pickle

pickle.dump(model, open("/content/drive/MyDrive/SpamProject/model.pkl", "wb"))
pickle.dump(vectorizer, open("/content/drive/MyDrive/SpamProject/vectorizer.pkl", "wb"))